# Generated by Django 4.1.4 on 2022-12-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ExpressFoodApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("items", models.CharField(max_length=300)),
                ("nom", models.CharField(max_length=300)),
                ("prenom", models.CharField(max_length=300)),
                ("email", models.EmailField(max_length=254)),
                ("adress", models.CharField(max_length=300)),
                ("ville", models.CharField(max_length=200)),
                ("zipcode", models.CharField(max_length=300)),
                ("date_commande", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-date_commande"],},
        ),
    ]
